import { MdArrowRight, MdDoneAll } from "react-icons/md";
import { FaTimes } from "react-icons/fa";
import { SiMicrosoftexchange } from "react-icons/si";
export const officeEnterprise = [
  {
    id: 0,
    item: "",
    version: "",
  },
  {
    id: 1,
    item: "Office-365 plus",
    version: "Pro Plus",
  },
  {
    id: 2,
    item: "Office-365 Enterprise",
    version: "E1",
  },
  {
    id: 3,
    item: "Office-365 Enterprise",
    version: "E3",
  },
  {
    id: 4,
    item: "Office-365 Enterprise",
    version: "E6",
  },
];
export const description = [
  {
    id: 0,
    keyPoint: "Maximum Users",
    plus: "unlimited",
    E1: "unlimited",
    E3: "unlimited",
    E6: "unlimited",
  },
  {
    id: 1,
    keyPoint: "Up-To-Date Desktop Applications",
    plus: <MdDoneAll className=" text-green-500" />,
    E1: <FaTimes className=" text-red-600" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 2,
    keyPoint: "Mobile App",
    plus: <MdDoneAll className=" text-green-500" />,
    E1: <MdDoneAll className=" text-green-500" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 3,
    keyPoint: "Office Web Applications",
    plus: <MdDoneAll className=" text-green-500" />,
    E1: <MdDoneAll className=" text-green-500" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 4,
    keyPoint: "Online File Storage (GB)",
    plus: 1024,
    E1: 1024,
    E3: 1024,
    E6: 1024,
  },
  {
    id: 5,
    keyPoint: "MailBox size",
    plus: <FaTimes className=" text-red-600" />,
    E1: 1024,
    E3: 1024,
    E6: 1024,
  },
  {
    id: 6,
    keyPoint: "Business Class Email,Calendar and Contacts",
    plus: <FaTimes className=" text-red-600" />,
    E1: <MdDoneAll className=" text-green-500" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 7,
    keyPoint: "Host Online & VideoConfresing Meetings",
    plus: <FaTimes className=" text-red-600" />,
    E1: "Up To 250 People",
    E3: "Up To 250 People",
    E6: "Up To 250 People",
  },
  {
    id: 8,
    keyPoint: "Corporate Social Network",
    plus: <FaTimes className=" text-red-600" />,
    E1: <FaTimes className=" text-red-600" />,
    E3: <FaTimes className=" text-red-600" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 9,
    keyPoint: "Self Services Business Inteligence",
    plus: <MdDoneAll className=" text-green-500" />,
    E1: <FaTimes className=" text-red-600" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 10,
    keyPoint: "Cloud PBX and PXTN confrencing",
    plus: <FaTimes className=" text-red-600" />,
    E1: <FaTimes className=" text-red-600" />,
    E3: <FaTimes className=" text-red-600" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
];

export const securityData = [
  {
    id: 0,
    type: "Manage User Credential and Permission",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 1,
    type: "Single Sign-On(SOS)",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 2,
    type: "Data Policy",
    status: "Not Used For Advertising",
  },
  {
    id: 3,
    type: "Data Ownership",
    status: "Customer",
  },
  {
    id: 4,
    type: "Encryped At Rest & In Transit",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 5,
    type: "Regular Data Backup",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 6,
    type: "In Region Data Centers",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 7,
    type: "Secure Data Center Envorment",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 8,
    type: "Remotly Wipe Data From Mobile Devices",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 9,
    type: "Multi Factor Authantication",
    status: <MdDoneAll className=" text-green-500" />,
  },
];

export const relabilityData = [
  {
    id: 0,
    type: "Guaranted Uptime(%)",
    status: "99.9",
  },
  {
    id: 1,
    type: "Financially Backed SLA",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 2,
    type: "Proactive Monitoring",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 3,
    type: "Automated provisioning Process",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 4,
    type: "Updates Include In Subscription",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 5,
    type: "Maintain Multiple Copies of Data Across Multiple Datacenteres That You Are Aware Of",
    status: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 6,
    type: "Through Review of Any Services Incident Regardless of Magnitude",
    status: <MdDoneAll className=" text-green-500" />,
  },
];
export const enterpriseApplicationData = [
  {
    id: 0,
    name: "Exchange",
    icon: require("../app/assets/images/exchange.png"),
    ProPlus: <FaTimes className=" text-red-600" />,
    E1: <MdDoneAll className=" text-green-500" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 1,
    name: "OutLook",
    icon: require("../app/assets/images/outlook.png"),
    ProPlus: "Desktop Web",
    E1: <FaTimes className=" text-red-600" />,
    E3: "Desktop Web",
    E6: "Desktop Web",
  },
  {
    id: 2,
    name: "Microsoft Word",
    icon: require("../app/assets/images/word.png"),
    ProPlus: "Desktop Web",
    E1: <FaTimes className=" text-red-600" />,
    E3: "Desktop Web",
    E6: "Desktop Web",
  },
  {
    id: 3,
    name: "Excel",
    icon: require("../app/assets/images/excel.png"),
    ProPlus: "Desktop Web",
    E1: <FaTimes className=" text-red-600" />,
    E3: "Desktop Web",
    E6: "Desktop Web",
  },
  {
    id: 4,
    name: "Publisher",
    icon: require("../app/assets/images/publisher.png"),
    ProPlus: <FaTimes className=" text-red-600" />,
    E1: <FaTimes className=" text-red-600" />,
    E3: <FaTimes className=" text-red-600" />,
    E6: <FaTimes className=" text-red-600" />,
  },
  {
    id: 5,
    name: "PowerPoint",
    icon: require("../app/assets/images/pp.png"),
    ProPlus: "Desktop Web",
    E1: <FaTimes className=" text-red-600" />,
    E3: "Desktop Web",
    E6: "Desktop Web",
  },
  {
    id: 6,
    name: "OneNote",
    icon: require("../app/assets/images/oneNote.png"),
    ProPlus: "Desktop Web",
    E1: <FaTimes className=" text-red-600" />,
    E3: "Desktop Web",
    E6: "Desktop Web",
  },
  {
    id: 7,
    name: "Access",
    icon: require("../app/assets/images/acess.png"),
    ProPlus: "Desktop (PC Only)",
    E1: <FaTimes className=" text-red-600" />,
    E3: "Desktop (PC Only)",
    E6: "Desktop (PC Only)",
  },
  {
    id: 8,
    name: "OneDrive",
    icon: require("../app/assets/images/onedrive.png"),
    ProPlus: <MdDoneAll className=" text-green-500" />,
    E1: <MdDoneAll className=" text-green-500" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 9,
    name: "Skype For Business",
    icon: require("../app/assets/images/skype.png"),
    ProPlus: <FaTimes className=" text-red-600" />,
    E1: <MdDoneAll className=" text-green-500" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 10,
    name: "Yammer",
    icon: require("../app/assets/images/yammer.png"),
    ProPlus: <FaTimes className=" text-red-600" />,
    E1: <MdDoneAll className=" text-green-500" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 11,
    name: "Teams",
    icon: require("../app/assets/images/teams.png"),
    ProPlus: <FaTimes className=" text-red-600" />,
    E1: <MdDoneAll className=" text-green-500" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 12,
    name: "Sharepoint",
    icon: require("../app/assets/images/sharepoint.png"),
    ProPlus: <FaTimes className=" text-red-600" />,
    E1: <MdDoneAll className=" text-green-500" />,
    E3: <MdDoneAll className=" text-green-500" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
  {
    id: 13,
    name: "Power BI",
    icon: require("../app/assets/images/powerBI.png"),
    ProPlus: <FaTimes className=" text-red-600" />,
    E1: <FaTimes className=" text-red-600" />,
    E3: <FaTimes className=" text-red-600" />,
    E6: <MdDoneAll className=" text-green-500" />,
  },
];
